version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: go_microservice_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_user_pswd
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "7777:5432" # external port : internal port
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  app:
    build: .
    container_name: go_microservice_app
    restart: unless-stopped
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=appdb
      - DB_USERNAME=app_user
      - DB_PASSWORD=app_user_pswd
    depends_on:
      - postgres
    ports:
      - "9898:9898"
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "go mod download && go run ."