version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: go_microservice_minio
    restart: unless-stopped
    ports:
    - "5001:9000"
    - "5002:9001"
    environment:
      MINIO_ROOT_USER: micro_user
      MINIO_ROOT_PASSWORD: micro_user_pswd
      MINIO_DEFAULT_BUCKETS: "user-bucket"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s
    volumes:
      - minio_data:/data

  app:
    build: .
    container_name: go_microservice_app
    restart: unless-stopped
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_USER=micro_user
      - MINIO_PASSWORD=micro_user_pswd
      - MINIO_BUCKET=user-bucket
      - MINIO_FILE=users.json
    depends_on:
      - minio
    ports:
      - "9898:9898"
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "go mod download && go run ."

  prometheus:
    image: prom/prometheus:latest
    container_name: go_microservice_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"  # Web UI Prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: go_microservice_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"  # Web UI Grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123  # Измените пароль!
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  minio_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local